# Generated by Django 5.0.1 on 2024-02-25 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("author_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("works", models.TextField()),
                ("contact", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                ("book_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("pub_date", models.DateTimeField(verbose_name="Publish date")),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("authors", models.ManyToManyField(to="bookstore.author")),
            ],
        ),
    ]
