# Generated by Django 5.0.1 on 2024-02-26 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookstore", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="pub_date",
            field=models.DateField(verbose_name="Publish date"),
        ),
    ]
